version: '3.8'
services:

  selenoid:
    network_mode: bridge
    container_name: selenoid
    image: "aerokube/selenoid:latest"
    ports:
      - "4445:4444"
    volumes:
      - "/Users/lballetti/Documents/GitHub/competency-center/selenoid/:/etc/selenoid"
      - "/Users/lballetti/Documents/GitHub/competency-center/selenoid/video:/opt/selenoid/video"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/lballetti/Documents/GitHub/competency-center/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video"]
      
  selenoid-ui:
    network_mode: bridge
    container_name: selenoid-ui
    image: "imagenarium/selenoid-ui:1.10.5"
    ports:
      - "8090:8080"
    links:
      - ggr-ui
    command:
      ["--selenoid-uri", "http://ggr-ui:8888"]

  ggr:
    image: "mag1art/ggr:latest"
    container_name: ggr
    network_mode: bridge
    ports:
        - "4444:4444"
    volumes:
        - "/etc/grid-router/:/etc/grid-router:ro"
    restart: always

  ggr-ui:
    image: 'mag1art/ggr-ui:latest'
    container_name: ggr-ui
    network_mode: bridge
    ports:
      - '8888:8888'
    volumes:
      - '/etc/grid-router/quota:/etc/grid-router/quota:ro'
    restart: always